ControleDeContatos/Controllers/AlterarSenhaController.cs
using ControleDeContatos.Helper;
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {

                UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;

                if(ModelState.IsValid)
                {
                    _usuarioRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }
                return View("Index", alterarSenhaModel);
            }
            catch(Exception e)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar sua senha, tente novamente, detalhe do erro: {e.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

ControleDeContatos/Views/AlterarSenha/Index.cshtml
@using ControleDeContatos.Enums;
@model AlterarSenhaModel
@{
    ViewData["Title"] = "Alterar senha do usuário -";
}

<div class="text-center">
    <h3 class="display-4">Alterar senha do usuário</h3>
</div>

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]
    </div>
}
<br />

<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">

    <div class="mb-3">
        <label for="senhaAtual" class="form-label">Senha Atual</label>
        <input type="password" class="form-control" asp-for="SenhaAtual" placeholder="Digite a senha atual do usuário">
        @Html.ValidationMessageFor(x => x.SenhaAtual)
    </div>
    <div class="mb-3">
        <label for="novaSenha" class="form-label">Nova Senha</label>
        <input type="password" class="form-control" asp-for="NovaSenha" placeholder="Digite a nova senha do usuário">
        @Html.ValidationMessageFor(x => x.NovaSenha)
    </div>
    <div class="mb-3">
        <label for="confirmarSenha" class="form-label">Confirmar Nova Senha</label>
        <input type="password" class="form-control" asp-for="ConfirmarNovaSenha" placeholder="Digite a confirmação da nova senha do usuário">
        @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
    </div>

    <button type="submit" class="btn btn-primary w-100">Alterar</button>
    <a role="button" class="btn btn-secondary w-100 mt-1" asp-controller="Home" asp-action="Index">Voltar</a>
</form>